/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CTIP;

public class App1231
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
