/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CTIP;

public class App {
    int a;  //NO use
    public String getGreeting() {
        
        return "Hello world.";
    }

    public static void main(String[] args) {
        int b;
        b=2;
        b=3;
        System.out.println(new App().getGreeting());
    }
}
